version: '3.8'

services:
  fetcher:
    # Uncomment the following lines to build the image yourself
    # build:
    #   context: .
    #   dockerfile: fetcher/Dockerfile
    image: undeadjess/mcserverjars-fetcher:latest
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ExamplePassword-PleaseChange
      DB_NAME: mcserverjars
    depends_on:
      - db

  api:
    # Uncomment the following lines to build the image yourself
    # build:
    #   context: .
    #   dockerfile: api/Dockerfile
    image: undeadjess/mcserverjars-api:latest
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ExamplePassword-PleaseChange
      DB_NAME: mcserverjars
      LISTEN_PORT: 3002
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ExamplePassword-PleaseChange
      MYSQL_DATABASE: mcserverjars
    ports:
      - "3306:3306"

  # optional: phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ExamplePassword-PleaseChange
    ports:
      - "3003:80"
    depends_on:
      - db
