version: '3.8'

services:
  fetcher:
    build:
      context: .
      dockerfile: fetcher/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ExamplePassword-PleaseChange
      DB_NAME: mcserverjars
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ExamplePassword-PleaseChange
      DB_NAME: mcserverjars
      LISTEN_PORT: 3002
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ExamplePassword-PleaseChange
      MYSQL_DATABASE: mcserverjars
    ports:
      - "3306:3306"
