services:
  fetcher:
    # Uncomment the following lines to build the image yourself (clone the repo first)
    # build:
    #   context: fetcher/
    #   dockerfile: Dockerfile
    image: ghcr.io:undeadjess/serverjars-fetcher:testing
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ExamplePassword-PleaseChange
      DB_NAME: mcserverjars
    depends_on:
      db:
        condition: service_healthy

  api:
    # Uncomment the following lines to build the image yourself (clone the repo first)
    # build:
    #   context: api/
    #   dockerfile: Dockerfile
    image: ghcr.io:undeadjess/serverjars-api:testing
    restart: always
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ExamplePassword-PleaseChange
      DB_NAME: mcserverjars
      LISTEN_PORT: 3002
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ExamplePassword-PleaseChange
      MYSQL_DATABASE: mcserverjars
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # optional: adminer
  adminer:
    image: adminer
    ports:
      - "3003:8080"
    depends_on:
      - db