name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push fetcher image
      uses: docker/build-push-action@v5
      with:
        context: ./fetcher/
        file: ./fetcher/Dockerfile
        push: true
        tags: undeadjess/mcserverjars-fetcher:latest

    - name: Build and push api image
      uses: docker/build-push-action@v5
      with:
        context: ./api/
        file: ./api/Dockerfile
        push: true
        tags: undeadjess/mcserverjars-api:latest